Add -gstabs+ option if supported (based on a patch by Marcus Meissner).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10548,6 +10548,58 @@ echo "${ECHO_T}$ac_cv_c_gcc_stack_boundary" >&6
   then
     CFLAGS="$CFLAGS -mpreferred-stack-boundary=2"
   fi
+
+    echo "$as_me:$LINENO: checking for gcc -gstabs+ support" >&5
+echo $ECHO_N "checking for gcc -gstabs+ support... $ECHO_C" >&6
+if test "${ac_cv_c_gcc_gstabs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_wine_try_cflags_saved=$CFLAGS
+CFLAGS="$CFLAGS -gstabs+"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_gcc_gstabs="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_gcc_gstabs="no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+CFLAGS=$ac_wine_try_cflags_saved
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_gcc_gstabs" >&5
+echo "${ECHO_T}$ac_cv_c_gcc_gstabs" >&6
+  if test "$ac_cv_c_gcc_gstabs" = "yes"
+  then
+    CFLAGS="$CFLAGS -gstabs+"
+  fi
 fi
 
 
