configure: Improve the check for the GLU library.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1388,6 +1388,7 @@ Optional Packages:
   --without-esd           do not use the EsounD sound support
   --without-fontconfig    do not use fontconfig
   --without-gphoto        do not use gphoto (Digital Camera support)
+  --without-glu           do not use the GLU library
   --without-hal           do not use HAL (dynamic device support)
   --without-jack          do not use the Jack sound support
   --without-jpeg          do not use JPEG
@@ -1969,6 +1970,12 @@ fi
 # Check whether --with-gphoto was given.
 if test "${with_gphoto+set}" = set; then
   withval=$with_gphoto;
+fi
+
+
+# Check whether --with-glu was given.
+if test "${with_glu+set}" = set; then
+  withval=$with_glu; if test "x$withval" = "xno"; then ac_cv_header_GL_glu_h=no; fi
 fi
 
 
@@ -11089,15 +11096,16 @@ _ACEOF
 
 fi
 
-
-	        		{ echo "$as_me:$LINENO: checking for gluLookAt in -lGLU" >&5
-echo $ECHO_N "checking for gluLookAt in -lGLU... $ECHO_C" >&6; }
-if test "${ac_cv_lib_GLU_gluLookAt+set}" = set; then
+                 if test "$ac_cv_header_GL_glu_h" = "yes"
+                 then
+                    { echo "$as_me:$LINENO: checking for -lGLU" >&5
+echo $ECHO_N "checking for -lGLU... $ECHO_C" >&6; }
+if test "${ac_cv_lib_soname_GLU+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
+  ac_check_soname_save_LIBS=$LIBS
 LIBS="-lGLU $OPENGL_LIBS $X_LIBS $X_PRE_LIBS -lXext -lX11 -lm $X_EXTRA_LIBS $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -11137,24 +11145,49 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_GLU_gluLookAt=yes
+  case "$LIBEXT" in
+    dll) ;;
+    dylib) ac_cv_lib_soname_GLU=`otool -L conftest$ac_exeext | grep "libGLU\\.[0-9A-Za-z.]*dylib" | sed -e "s/^.*\/\(libGLU\.[0-9A-Za-z.]*dylib\).*$/\1/"';2,$d'` ;;
+    *) ac_cv_lib_soname_GLU=`$ac_cv_path_LDD conftest$ac_exeext | grep "libGLU\\.$LIBEXT" | sed -e "s/^.*\(libGLU\.$LIBEXT[^	 ]*\).*$/\1/"';2,$d'` ;;
+  esac
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_GLU_gluLookAt=no
+
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
+  LIBS=$ac_check_soname_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_GLU_gluLookAt" >&5
-echo "${ECHO_T}$ac_cv_lib_GLU_gluLookAt" >&6; }
-if test $ac_cv_lib_GLU_gluLookAt = yes; then
-  OPENGL_LIBS="$OPENGL_LIBS -lGLU"
-			     GLU32FILES='$(GLU32FILES)'
+if test "x$ac_cv_lib_soname_GLU" = "x"; then
+  { echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
 
+else
+  { echo "$as_me:$LINENO: result: $ac_cv_lib_soname_GLU" >&5
+echo "${ECHO_T}$ac_cv_lib_soname_GLU" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define SONAME_LIBGLU "$ac_cv_lib_soname_GLU"
+_ACEOF
+
+       OPENGL_LIBS="$OPENGL_LIBS -lGLU"
+                                                     GLU32FILES='$(GLU32FILES)'
+fi
+
+                 fi
+                 if test "x$ac_cv_lib_soname_GLU" = "x"; then
+  case "x$with_glu" in
+  x)   wine_notices="$wine_notices|libGLU development files not found, GLU won't be supported." ;;
+  xno) ;;
+  *)   { { echo "$as_me:$LINENO: error: libGLU development files not found, GLU won't be supported.
+This is an error since --with-glu was requested." >&5
+echo "$as_me: error: libGLU development files not found, GLU won't be supported.
+This is an error since --with-glu was requested." >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
 fi
 
              else
