Added sigsetjmp/siglongjmp and gettid to the portability library.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9706,6 +9706,62 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for sigsetjmp" >&5
+echo $ECHO_N "checking for sigsetjmp... $ECHO_C" >&6
+if test "${ac_cv_c_sigsetjmp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <setjmp.h>
+int
+main ()
+{
+sigjmp_buf buf;
+    sigsetjmp( buf, 1 );
+    siglongjmp( buf, 1 );
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_sigsetjmp="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_sigsetjmp="no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_sigsetjmp" >&5
+echo "${ECHO_T}$ac_cv_c_sigsetjmp" >&6
+if test "$ac_cv_c_sigsetjmp" = "yes"
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SIGSETJMP 1
+_ACEOF
+
+fi
+
 echo "$as_me:$LINENO: checking for pthread_rwlock_t" >&5
 echo $ECHO_N "checking for pthread_rwlock_t... $ECHO_C" >&6
 if test "${ac_cv_type_pthread_rwlock_t+set}" = set; then
@@ -13800,6 +13856,7 @@ fi
 
 
 
+
 for ac_func in \
 	_lwp_create \
 	_lwp_self \
@@ -13824,6 +13881,7 @@ for ac_func in \
 	getprotobynumber \
 	getpwuid \
 	getservbyport \
+	gettid \
 	gettimeofday \
 	inet_network \
 	lseek64 \
