Initial version of the Wine preloader, used to reserve memory areas at startup. Based on the work of Mike McCormack.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14180,31 +14180,44 @@ echo "${ECHO_T}$ac_cv_c_export_dynamic" >&6
 
         case $host_cpu in
           *i[3456789]86*)
-            echo "$as_me:$LINENO: checking whether we can relocate the executable to 0x00110000" >&5
-echo $ECHO_N "checking whether we can relocate the executable to 0x00110000... $ECHO_C" >&6
+            echo "$as_me:$LINENO: checking whether we can relocate the executable to 0x77f00000" >&5
+echo $ECHO_N "checking whether we can relocate the executable to 0x77f00000... $ECHO_C" >&6
 if test "${ac_cv_ld_reloc_exec+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  saved_CFLAGS="$CFLAGS"
-               CFLAGS="$CFLAGS -Wl,--section-start,.interp=0x00110400"
-               if test "$cross_compiling" = yes; then
-  ac_cv_ld_reloc_exec="no"
-else
-  cat >conftest.$ac_ext <<_ACEOF
+  ac_wine_try_cflags_saved=$CFLAGS
+CFLAGS="$CFLAGS -Wl,--section-start,.interp=0x77f00400"
+cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <unistd.h>
-                           int main() { return (sbrk(32*1024*1024) == (void *)-1); }
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
 _ACEOF
-rm -f conftest$ac_exeext
+rm -f conftest.$ac_objext conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -14212,22 +14225,20 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   ac_cv_ld_reloc_exec="yes"
 else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
+  echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-( exit $ac_status )
 ac_cv_ld_reloc_exec="no"
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-               CFLAGS="$saved_CFLAGS"
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+CFLAGS=$ac_wine_try_cflags_saved
 fi
 echo "$as_me:$LINENO: result: $ac_cv_ld_reloc_exec" >&5
 echo "${ECHO_T}$ac_cv_ld_reloc_exec" >&6
             if test "$ac_cv_ld_reloc_exec" = "yes"
             then
-              LDEXECFLAGS="$LDEXECFLAGS -Wl,--section-start,.interp=0x00110400"
+              LDEXECFLAGS="$LDEXECFLAGS -Wl,--section-start,.interp=0x77f00400"
             fi
             ;;
         esac
@@ -14528,7 +14539,7 @@ esac
 
 case $host_os in
   linux*)
-    WINE_BINARIES="wine-glibc wine-kthread wine-pthread"
+    WINE_BINARIES="wine-glibc wine-kthread wine-pthread wine-preloader"
 
     MAIN_BINARY="wine-glibc"
 
