winex11.drv: Load the XComposite extension when available.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9239,6 +9239,7 @@ fi
 
 
 
+
 for ac_header in X11/Xlib.h \
                       X11/XKBlib.h \
                       X11/Xutil.h \
@@ -9246,6 +9247,7 @@ for ac_header in X11/Xlib.h \
                       X11/extensions/shape.h \
                       X11/extensions/XInput.h \
                       X11/extensions/XShm.h \
+                      X11/extensions/Xcomposite.h \
                       X11/extensions/Xinerama.h \
                       X11/extensions/Xrandr.h \
                       X11/extensions/Xrender.h \
@@ -10194,6 +10196,93 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
         if test "x$ac_cv_lib_soname_Xinerama" = "x"; then
   wine_notices="$wine_notices|Xinerama development files not found.
 Wine will be built without Xinerama support. (winex11.drv)"
+fi
+
+
+                if test "$ac_cv_header_X11_extensions_Xcomposite_h" = "yes"
+        then
+            { echo "$as_me:$LINENO: checking for -lXcomposite" >&5
+echo $ECHO_N "checking for -lXcomposite... $ECHO_C" >&6; }
+if test "${ac_cv_lib_soname_Xcomposite+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_soname_save_LIBS=$LIBS
+LIBS="-lXcomposite $X_LIBS -lXext -lX11 $X_EXTRA_LIBS $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char XCompositeRedirectWindow ();
+int
+main ()
+{
+return XCompositeRedirectWindow ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  case "$LIBEXT" in
+    dll) ;;
+    dylib) ac_cv_lib_soname_Xcomposite=`otool -L conftest$ac_exeext | grep "libXcomposite\\.[0-9A-Za-z.]*dylib" | sed -e "s/^.*\/\(libXcomposite\.[0-9A-Za-z.]*dylib\).*$/\1/"';2,$d'` ;;
+    *) ac_cv_lib_soname_Xcomposite=`$ac_cv_path_LDD conftest$ac_exeext | grep "libXcomposite\\.$LIBEXT" | sed -e "s/^.*\(libXcomposite\.$LIBEXT[^	 ]*\).*$/\1/"';2,$d'` ;;
+  esac
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+  LIBS=$ac_check_soname_save_LIBS
+fi
+if test "x$ac_cv_lib_soname_Xcomposite" = "x"; then
+  { echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6; }
+
+else
+  { echo "$as_me:$LINENO: result: $ac_cv_lib_soname_Xcomposite" >&5
+echo "${ECHO_T}$ac_cv_lib_soname_Xcomposite" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define SONAME_LIBXCOMPOSITE "$ac_cv_lib_soname_Xcomposite"
+_ACEOF
+
+
+fi
+
+        fi
+        if test "x$ac_cv_lib_soname_Xcomposite" = "x"; then
+  wine_notices="$wine_notices|XComposite development files not found.
+Wine will be built without XComposite support. (winex11.drv)"
 fi
 
 
