When checking for sys/mount.h and sys/user.h also include sys/types.h if available.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11645,8 +11645,6 @@ done
 
 
 
-
-
 for ac_header in \
 	arpa/inet.h \
 	arpa/nameser.h \
@@ -11688,7 +11686,6 @@ for ac_header in \
 	sys/lwp.h \
 	sys/mman.h \
 	sys/modem.h \
-	sys/mount.h \
 	sys/msg.h \
 	sys/param.h \
 	sys/poll.h \
@@ -11706,7 +11703,6 @@ for ac_header in \
 	sys/times.h \
 	sys/uio.h \
 	sys/un.h \
-	sys/user.h \
 	sys/v86.h \
 	sys/v86intr.h \
 	sys/vfs.h \
@@ -11884,6 +11880,58 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+
+
+
+
+for ac_header in sys/mount.h sys/user.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#if HAVE_SYS_TYPES_H
+     # include <sys/types.h>
+     #endif
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
 
 
 
