Make use of .half and/or .asciiz assembler keywords when necessary.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11141,7 +11141,125 @@ if test "$ac_cv_c_asm_string" = "yes"
 then
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_ASM_STRING 1
+#define __ASM_STRING ".string"
+_ACEOF
+
+else
+    echo "$as_me:$LINENO: checking whether assembler accepts .asciz" >&5
+echo $ECHO_N "checking whether assembler accepts .asciz... $ECHO_C" >&6
+if test "${ac_cv_c_asm_asciz+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+void ac_asm(void) { asm(".data\n\t.asciz \"test\"\n\t.text"); }
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_asm_asciz="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_asm_asciz="no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_asm_asciz" >&5
+echo "${ECHO_T}$ac_cv_c_asm_asciz" >&6
+    if test "$ac_cv_c_asm_asciz" = "yes"
+    then
+      cat >>confdefs.h <<\_ACEOF
+#define __ASM_STRING ".asciz"
+_ACEOF
+
+    else
+      cat >>confdefs.h <<\_ACEOF
+#define __ASM_STRING ".ascii"
+_ACEOF
+
+    fi
+fi
+
+
+echo "$as_me:$LINENO: checking whether assembler accepts .short" >&5
+echo $ECHO_N "checking whether assembler accepts .short... $ECHO_C" >&6
+if test "${ac_cv_c_asm_short+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+void ac_asm(void) { asm(".data\n\t.short 1\n\t.text"); }
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_asm_short="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_asm_short="no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_asm_short" >&5
+echo "${ECHO_T}$ac_cv_c_asm_short" >&6
+if test "$ac_cv_c_asm_short" = "yes"
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define __ASM_SHORT ".short"
+_ACEOF
+
+else
+  cat >>confdefs.h <<\_ACEOF
+#define __ASM_SHORT ".half"
 _ACEOF
 
 fi
