sane.ds: Dynamically load libsane.so.
This change was triggered because of a bug in libsane-hpaio.so, namely
that it relies on libsane.so being dlopen'd RTLD_GLOBAL so that
sanei_init_debug can be resolved.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15720,6 +15720,82 @@ _ACEOF
 
 fi
 
+  { echo "$as_me:$LINENO: checking for -lsane soname" >&5
+echo $ECHO_N "checking for -lsane soname... $ECHO_C" >&6; }
+if test "${ac_cv_lib_soname_sane+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_get_soname_save_LIBS=$LIBS
+LIBS="-lsane  $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sane_init ();
+int
+main ()
+{
+return sane_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  case "$LIBEXT" in
+    dylib) ac_cv_lib_soname_sane=`otool -L conftest$ac_exeext | grep libsane\\.[0-9A-Za-z.]*dylib | sed -e "s/^.*\/\(libsane\.[0-9A-Za-z.]*dylib\).*$/\1/"';2,$d'` ;;
+    so) ac_cv_lib_soname_sane=`$ac_cv_path_LDD conftest$ac_exeext | grep libsane\\.so | sed -e "s/^.*\(libsane\.so[^	 ]*\).*$/\1/"';2,$d'` ;;
+  esac
+  if test "x$ac_cv_lib_soname_sane" = "x"
+  then
+     ac_cv_lib_soname_sane="libsane.$LIBEXT"
+  fi
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_soname_sane="libsane.$LIBEXT"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+  LIBS=$ac_get_soname_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_soname_sane" >&5
+echo "${ECHO_T}$ac_cv_lib_soname_sane" >&6; }
+if test "${ac_cv_lib_soname_sane+set}" = set; then
+
+cat >>confdefs.h <<_ACEOF
+#define SONAME_LIBSANE "$ac_cv_lib_soname_sane"
+_ACEOF
+
+fi
+
 fi
 
 
