secur32: Check that the GnuTLS header is recent enough for schannel.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12881,6 +12881,38 @@ echo "${ECHO_T}$ac_cv_header_gnutls_gnutls_h" >&6; }
 
 fi
 if test $ac_cv_header_gnutls_gnutls_h = yes; then
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <gnutls/gnutls.h>
+int
+main ()
+{
+typeof(gnutls_transport_set_errno) *pfunc;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
   { echo "$as_me:$LINENO: checking for -lgnutls" >&5
 echo $ECHO_N "checking for -lgnutls... $ECHO_C" >&6; }
 if test "${ac_cv_lib_soname_gnutls+set}" = set; then
@@ -12960,6 +12992,14 @@ _ACEOF
 
 fi
 
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 
 
