winex11.drv: Add Xcursor support for 32 bit cursors.
Based on patch by Henri Verbeet.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7672,9 +7672,11 @@ then
 
 
 
+
 for ac_header in X11/Xlib.h \
                       X11/XKBlib.h \
                       X11/Xutil.h \
+                      X11/Xcursor/Xcursor.h \
                       X11/extensions/shape.h \
                       X11/extensions/XInput.h \
                       X11/extensions/XShm.h \
@@ -14720,6 +14722,82 @@ if test "${ac_cv_lib_soname_Xrandr+set}" = set; then
 
 cat >>confdefs.h <<_ACEOF
 #define SONAME_LIBXRANDR "$ac_cv_lib_soname_Xrandr"
+_ACEOF
+
+fi
+
+  { echo "$as_me:$LINENO: checking for -lXcursor soname" >&5
+echo $ECHO_N "checking for -lXcursor soname... $ECHO_C" >&6; }
+if test "${ac_cv_lib_soname_Xcursor+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_get_soname_save_LIBS=$LIBS
+LIBS="-lXcursor $X_LIBS -lX11 $X_EXTRA_LIBS $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char XcursorImageLoadCursor ();
+int
+main ()
+{
+return XcursorImageLoadCursor ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  case "$LIBEXT" in
+    dylib) ac_cv_lib_soname_Xcursor=`otool -L conftest$ac_exeext | grep libXcursor\\.[0-9A-Za-z.]*dylib | sed -e "s/^.*\/\(libXcursor\.[0-9A-Za-z.]*dylib\).*$/\1/"';2,$d'` ;;
+    so) ac_cv_lib_soname_Xcursor=`$ac_cv_path_LDD conftest$ac_exeext | grep libXcursor\\.so | sed -e "s/^.*\(libXcursor\.so[^	 ]*\).*$/\1/"';2,$d'` ;;
+  esac
+  if test "x$ac_cv_lib_soname_Xcursor" = "x"
+  then
+     ac_cv_lib_soname_Xcursor="libXcursor.$LIBEXT"
+  fi
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_soname_Xcursor="libXcursor.$LIBEXT"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+  LIBS=$ac_get_soname_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_soname_Xcursor" >&5
+echo "${ECHO_T}$ac_cv_lib_soname_Xcursor" >&6; }
+if test "${ac_cv_lib_soname_Xcursor+set}" = set; then
+
+cat >>confdefs.h <<_ACEOF
+#define SONAME_LIBXCURSOR "$ac_cv_lib_soname_Xcursor"
 _ACEOF
 
 fi
