configure: Moved the crosstest checks so that they are done for all platforms.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -733,9 +733,9 @@ LDEXECFLAGS
 DISKARBITRATIONLIB
 COREAUDIO
 CARBONLIB
-CROSSTEST
 CROSSCC
 CROSSWINDRES
+CROSSTEST
 NASLIBS
 XML2LIBS
 XML2INCL
@@ -9389,12 +9389,28 @@ echo "${ECHO_T}$ac_cv_c_dll_hpux" >&6; }
         fi
       fi
     fi
+    ;;
+esac
 
-        CROSSTEST=""
+enable_winequartz_drv=${enable_winequartz_drv:-no}
 
-    if test "$cross_compiling" = "no"
-    then
-      for ac_prog in i586-mingw32msvc-gcc i386-mingw32msvc-gcc i686-mingw32-gcc i586-mingw32-gcc i486-mingw32-gcc i386-mingw32-gcc mingw32-gcc mingw-gcc
+if test "$LIBEXT" = "a"; then
+  { { echo "$as_me:$LINENO: error: could not find a way to build shared libraries.
+It is currently not possible to build Wine without shared library
+(.so) support to allow transparent switch between .so and .dll files.
+If you are using Linux, you will need a newer binutils.
+" >&5
+echo "$as_me: error: could not find a way to build shared libraries.
+It is currently not possible to build Wine without shared library
+(.so) support to allow transparent switch between .so and .dll files.
+If you are using Linux, you will need a newer binutils.
+" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "$cross_compiling" = "no" -a "$LIBEXT" != "dll"
+then
+    for ac_prog in i586-mingw32msvc-gcc i386-mingw32msvc-gcc i686-mingw32-gcc i586-mingw32-gcc i486-mingw32-gcc i386-mingw32-gcc mingw32-gcc mingw-gcc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -9437,7 +9453,7 @@ fi
 done
 test -n "$CROSSCC" || CROSSCC="false"
 
-      for ac_prog in i586-mingw32msvc-dlltool i386-mingw32msvc-dlltool i686-mingw32-dlltool i586-mingw32-dlltool i486-mingw32-dlltool i386-mingw32-dlltool mingw32-dlltool mingw-dlltool
+    for ac_prog in i586-mingw32msvc-dlltool i386-mingw32msvc-dlltool i686-mingw32-dlltool i586-mingw32-dlltool i486-mingw32-dlltool i386-mingw32-dlltool mingw32-dlltool mingw-dlltool
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -9480,7 +9496,7 @@ fi
 done
 test -n "$DLLTOOL" || DLLTOOL="false"
 
-      for ac_prog in i586-mingw32msvc-windres i386-mingw32msvc-windres i686-mingw32-windres i586-mingw32-windres i486-mingw32-windres i386-mingw32-windres mingw32-windres mingw-windres
+    for ac_prog in i586-mingw32msvc-windres i386-mingw32msvc-windres i686-mingw32-windres i586-mingw32-windres i486-mingw32-windres i386-mingw32-windres mingw32-windres mingw-windres
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -9523,7 +9539,7 @@ fi
 done
 test -n "$CROSSWINDRES" || CROSSWINDRES="false"
 
-      for ac_prog in i586-mingw32msvc-ar i386-mingw32msvc-ar i686-mingw32-ar i586-mingw32-ar i486-mingw32-ar i386-mingw32-ar mingw32-ar mingw-ar
+    for ac_prog in i586-mingw32msvc-ar i386-mingw32msvc-ar i686-mingw32-ar i586-mingw32-ar i486-mingw32-ar i386-mingw32-ar mingw32-ar mingw-ar
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -9566,25 +9582,11 @@ fi
 done
 test -n "$MINGWAR" || MINGWAR="false"
 
-      if test "$CROSSCC" != "false"; then CROSSTEST="\$(CROSSTEST)"; fi
+    if test "$CROSSCC" != "false"
+    then
+        CROSSTEST="\$(CROSSTEST)"
+
     fi
-    ;;
-esac
-
-enable_winequartz_drv=${enable_winequartz_drv:-no}
-
-if test "$LIBEXT" = "a"; then
-  { { echo "$as_me:$LINENO: error: could not find a way to build shared libraries.
-It is currently not possible to build Wine without shared library
-(.so) support to allow transparent switch between .so and .dll files.
-If you are using Linux, you will need a newer binutils.
-" >&5
-echo "$as_me: error: could not find a way to build shared libraries.
-It is currently not possible to build Wine without shared library
-(.so) support to allow transparent switch between .so and .dll files.
-If you are using Linux, you will need a newer binutils.
-" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 
 
@@ -27164,9 +27166,9 @@ LDEXECFLAGS!$LDEXECFLAGS$ac_delim
 DISKARBITRATIONLIB!$DISKARBITRATIONLIB$ac_delim
 COREAUDIO!$COREAUDIO$ac_delim
 CARBONLIB!$CARBONLIB$ac_delim
-CROSSTEST!$CROSSTEST$ac_delim
 CROSSCC!$CROSSCC$ac_delim
 CROSSWINDRES!$CROSSWINDRES$ac_delim
+CROSSTEST!$CROSSTEST$ac_delim
 NASLIBS!$NASLIBS$ac_delim
 XML2LIBS!$XML2LIBS$ac_delim
 XML2INCL!$XML2INCL$ac_delim
