Abort if we do not find yacc or bison.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -55,6 +55,16 @@ AC_PROG_CPP
 AC_PATH_XTRA
 AC_PROG_YACC
 AC_PROG_LEX
+
+dnl **** Just additional warning checks, since AC_PROG just sets 'yacc' even
+dnl **** without one present.
+AC_CHECK_PROGS(XYACC,$YACC bison yacc,none)
+if test "$XYACC" = "none"
+then
+	echo "*** Error: No suitable bison/yacc found. ***"
+	echo "    Please install the 'bison' package."
+	exit 1
+fi
 AC_CHECK_PROGS(XLEX,$LEX flex lex,none)
 if test "$XLEX" = "none"
 then
