- Detection of .size instruction. - Detection of the assembler name prefix.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13357,6 +13357,71 @@ _ACEOF
 
 
 
+echo "$as_me:$LINENO: checking for .size in assembler" >&5
+echo $ECHO_N "checking for .size in assembler... $ECHO_C" >&6
+if test "${ac_cv_c_asm_size+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+void ac_asm(void) { asm(".globl _ac_test\n.size _ac_test, . - _ac_test"); }
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_asm_size="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_asm_size="no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_asm_size" >&5
+echo "${ECHO_T}$ac_cv_c_asm_size" >&6
+
+if test "$ac_cv_c_asm_size" = "yes"
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ASM_DOT_SIZE 1
+_ACEOF
+
+fi
+
+
 DLLEXT=""
 
 DLLFLAGS="-D_REENTRANT"
