Load any TrueType fonts that fontconfig knows about.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13086,6 +13086,71 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 fi
 
+echo "$as_me:$LINENO: checking for -lfontconfig soname" >&5
+echo $ECHO_N "checking for -lfontconfig soname... $ECHO_C" >&6
+if test "${ac_cv_lib_soname_fontconfig+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_get_soname_save_LIBS=$LIBS
+LIBS="-lfontconfig  $LIBS"
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char FcInit ();
+int
+main ()
+{
+FcInit ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_soname_fontconfig=`$ac_cv_path_LDD conftest$ac_exeext | grep libfontconfig\\.so | sed 's/^.*\(libfontconfig\.so[^	 ]*\).*$/\1/'`
+  if test "x$ac_cv_lib_soname_fontconfig" = "x"
+  then
+     ac_cv_lib_soname_fontconfig="libfontconfig.so"
+  fi
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_soname_fontconfig="libfontconfig.so"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  LIBS=$ac_get_soname_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_soname_fontconfig" >&5
+echo "${ECHO_T}$ac_cv_lib_soname_fontconfig" >&6
+if test "x$ac_cv_lib_soname_fontconfig" != xNONE
+then
+cat >>confdefs.h <<_ACEOF
+#define SONAME_LIBFONTCONFIG "$ac_cv_lib_soname_fontconfig"
+_ACEOF
+fi;
+
 echo "$as_me:$LINENO: checking for -lssl soname" >&5
 echo $ECHO_N "checking for -lssl soname... $ECHO_C" >&6
 if test "${ac_cv_lib_soname_ssl+set}" = set; then
@@ -13939,6 +14004,7 @@ done
 
 
 
+
 for ac_header in \
 	arpa/inet.h \
 	arpa/nameser.h \
@@ -13946,6 +14012,7 @@ for ac_header in \
 	direct.h \
 	elf.h \
 	float.h \
+	fontconfig/fontconfig.h \
 	getopt.h \
 	ieeefp.h \
 	io.h \
