Added version scripts for libwine and libwine_unicode.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13670,6 +13670,69 @@ _ACEOF
           LDDLL="$LDDLL,-init,__wine_spec_init,-fini,__wine_spec_fini"
         fi
 
+        echo "$as_me:$LINENO: checking whether the linker accepts version scripts" >&5
+echo $ECHO_N "checking whether the linker accepts version scripts... $ECHO_C" >&6
+if test "${ac_cv_c_ld_version_scripts+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  echo '{ global: *; };' >conftest.map
+           ac_wine_try_cflags_saved=$CFLAGS
+CFLAGS="$CFLAGS -fPIC -shared -Wl,--version-script=conftest.map"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_c_ld_version_scripts="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_c_ld_version_scripts="no"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+CFLAGS=$ac_wine_try_cflags_saved
+           rm -f conftest.map
+fi
+echo "$as_me:$LINENO: result: $ac_cv_c_ld_version_scripts" >&5
+echo "${ECHO_T}$ac_cv_c_ld_version_scripts" >&6
+        if test "$ac_cv_c_ld_version_scripts" = "yes"
+        then
+          LDSHARED="$LDSHARED \$(VERSCRIPT:%=-Wl,--version-script=%)"
+        fi
+
         echo "$as_me:$LINENO: checking whether the linker accepts --export-dynamic" >&5
 echo $ECHO_N "checking whether the linker accepts --export-dynamic... $ECHO_C" >&6
 if test "${ac_cv_c_export_dynamic+set}" = set; then
