Return 2 in case of a usage error. Use -z instead of comparing to an empty string.

diff --git a/tools/wineshelllink b/tools/wineshelllink
--- a/tools/wineshelllink
+++ b/tools/wineshelllink
@@ -45,7 +45,7 @@ options:
   --descr xx    application description
 
 EOF
-    exit 1
+    exit 2
 }
 
 if [ $# -eq 0 ] ; then
@@ -67,13 +67,13 @@ do
   esac
 done
 
-if [ "$mode" = ""  ] ; then
-    echo Either --desktop or --menu required
+if [ -z "$mode" ] ; then
+    echo "Either --desktop or --menu required"
     usage
 fi
 
-if [ "$link" = ""  ] ; then
-    echo You must specify a link name with --link
+if [ -z "$link" ] ; then
+    echo "You must specify a link name with --link"
     usage
 fi
 
